import React, { useState } from 'react';
import { Layout } from '@/components/Layout/Layout';
import { Table } from '@/components/UI/Table';
import { TableColumn } from '@/types';

export const Reports: React.FC = () => {
  const [searchValue, setSearchValue] = useState('');
  const [currentPage, setCurrentPage] = useState(1);

  const columns: TableColumn[] = [
    { key: 'reportId', label: 'Report ID', sortable: true },
    { key: 'type', label: 'Type', sortable: true },
    { key: 'generatedBy', label: 'Generated By', sortable: true },
    { key: 'date', label: 'Date', sortable: true },
    { key: 'status', label: 'Status', sortable: true },
  ];

  const mockData = [
    { reportId: 'RPT001', type: 'Monthly', generatedBy: 'Admin', date: '2024-01-31', status: 'Completed' },
    { reportId: 'RPT002', type: 'Weekly', generatedBy: 'Manager', date: '2024-01-28', status: 'Processing' },
  ];

  return (
    <Layout>
      <div className="space-y-6">
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Reports</h1>
        
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
          <Table
            columns={columns}
            data={mockData}
            searchValue={searchValue}
            onSearchChange={setSearchValue}
            currentPage={currentPage}
            totalPages={1}
            onPageChange={setCurrentPage}
          />
        </div>
      </div>
    </Layout>
  );
};